name: Deploy to EC2
'on':
  push:
    branches:
      - 'main'
jobs:
  integration:
    uses: ./.github/workflows/python-app.yml
    permissions:
      contents: read
      checks: write
  package_publish:
    uses: ./.github/workflows/docker-publish.yml
    permissions:
      contents: read
      checks: write
      packages: write
      id-token: write
  deploy:
    needs: [integration , package_publish ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: '54.152.79.128'
          username: '${{ secrets.EC2_USERNAME }}'
          key: '${{ secrets.EC2_SSH_KEY }}'
          script: >
            echo "login to root user"
            sudo su - root
          
            echo "Deleting the previous images & containers."
            docker stop $(docker ps -aq)
            docker rm $(docker ps -aq)
            docker rmi $(docker images -q)
            
            echo "Logging into GHCR..."
            echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u ${{
            secrets.GHCR_USERNAME }} --password-stdin
      
            echo "Pulling latest Docker image..."
            docker pull ghcr.io/${{secrets.secrets.GHCR_USERNAME}}/${{secrets.DOCKER_IMG_TAG}}
            
            echo "Running new container..."

            docker run -d -p ${{secrets.PORT}}:8085 ghcr.io/${{secrets.DOCKER_IMG_TAG}} 

            echo "Deployment completed!"
